### ISSUE TITLE
Negative Flux in astromodels

### ISSUE THREAD

**Issue by omodei** [threeML/astromodels#163]
Some users asked the possibility to have negative flux when doing their analysis, but the log transformation avoids the possibility to do this. Would be nice to have a way to disable log scaling.

**Comment by grburgess** [comment]
@omodei Ok, I've added the context managers and the ability to do this in the configuration.

to get an idea you can have a look at the test:

https://github.com/threeML/astromodels/blob/feature-native-node/astromodels/tests/test_parameter.py#L144

A word of caution, if someone fits with transforms and then tries to do a profile with them off... it will lead to incorrect results because the MLE point of a transformed parameters != MLE point of the non-transformed parameter except in a very few special cases of transforms.. and not log10.

**Comment by omodei** [comment]
Why this issue was reopened? I though you fix it.
